chore(release): remove leading zero from nuget version (#1000)
leading zero in Nuget version caused CI to fail on ffi crate build:

```
 error: invalid leading zero in minor version number
 --> ffi/Cargo.toml:3:11
  |
3 | version = "2025.09.24"
  |           ^^^^^^^^^^^^
  |
error: failed to load manifest for workspace member `/Users/runner/work/IronRDP/IronRDP/ffi`
referenced by workspace at `/Users/runner/work/IronRDP/IronRDP/Cargo.toml`
```